---
- hosts: denjos
  remote_user: denjos
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: install aptitude using apt
      apt:  name=aptitude state=latest update_cache=yes force_apt_get=yes
    - name: install required system packages
      apt: name={{item}} state=latest update_cache=yes
      loop: ['apt-transport-https','ca-certificates','curl','software-properties-common','python3-pip','virtualenv','python3-setuptools']
    - name: add docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present      
    - name: update apt and install docker-ce
      apt:  update_cache=yes name=docker-ce state=latest

