- hosts: orion
  remote_user: orion
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: task1
      apt: name={{item}} state=latest update_cache=yes force_apt_get=yes
      loop: ['bash','openssl','libssl-dev','libssl-doc','postgresql','postgresql-contrib','python','libpq-dev','python-psycopg2']
    - name: postgresql esta iniciado
      service:
        name: postgresql
        state: started
    - name: asegurar creacion de base de datos
      become: true
      become_user:  postgres
      postgresql_db:  name=oscar encoding=UTF-8 lc_collate=en_US.UTF-8 lc_ctype=en_US.UTF-8 template=template0 state=present
